2024-07-28 17:01:45,464 - ERROR - error_log.py:13 - 1048 (23000): Column 'user_id' cannot be null
Traceback (most recent call last):
  File "L:\personalprojects\studentmanager\venv\Lib\site-packages\mysql\connector\connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Table 'studentmanager.lenntecs_assistants' doesn't exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "L:\personalprojects\studentmanager\modules\agent\agent.py", line 21, in get_agent
    self.cursor.execute(f"SELECT agent_id FROM {self.agent_table} WHERE agent_name=%s", (self.agent_name,))
  File "L:\personalprojects\studentmanager\venv\Lib\site-packages\mysql\connector\cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\personalprojects\studentmanager\venv\Lib\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\personalprojects\studentmanager\venv\Lib\site-packages\mysql\connector\connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'studentmanager.lenntecs_assistants' doesn't exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "L:\personalprojects\studentmanager\venv\Lib\site-packages\mysql\connector\connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Column 'user_id' cannot be null

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "L:\personalprojects\studentmanager\modules\agent\agent.py", line 147, in save_thread_and_run
    self.cursor.execute(sql, (self.user_id, self.thread_id, self.run_id, chat))
  File "L:\personalprojects\studentmanager\venv\Lib\site-packages\mysql\connector\cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\personalprojects\studentmanager\venv\Lib\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\personalprojects\studentmanager\venv\Lib\site-packages\mysql\connector\connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.IntegrityError: 1048 (23000): Column 'user_id' cannot be null
